# Generated by Django 5.1 on 2024-12-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payment_payer_email_payment_payer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_payed',
            field=models.DecimalField(decimal_places=2, help_text='The total amount paid by the user.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency used for the payment (e.g., USD, EUR).', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_price',
            field=models.OneToOneField(help_text='Links a payment to a specific cart order.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myapp.cart'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(blank=True, help_text='Email address of the payer.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Name of the payer.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the payment was created.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_metadata',
            field=models.JSONField(blank=True, help_text='Raw metadata from the payment provider (e.g., PayPal).', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], default='PayPal', help_text='The method used for the payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paypal_id',
            field=models.CharField(blank=True, help_text='Unique PayPal transaction ID. Can be blank for non-PayPal methods.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', help_text='The current status of the payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transaction fee charged for the payment.', max_digits=10, null=True),
        ),
    ]
