# Generated by Django 5.1 on 2024-12-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_payment_options_remove_payment_amount_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_price',
            field=models.OneToOneField(blank=True, help_text='Links a payment to a specific cart order. This field is optional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myapp.cart'),
        ),
    ]
