# Generated by Django 5.1 on 2024-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_payment_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
